



const Privacy = () => {
    return (
        <>
            <div className='text-gray-400 block text-center my-4'> <a className='Googlefont mr-1' href="https://edenbigi.github.io/my-app/">Main Page</a>{">"}
                Privacy policy<div className='uppercase font-semibold text-black text-[30px]'>Privacy policy</div></div>
            <div className="Googlefont w-full px-16 sm:px-24 md:px-32 text-sm ">
                <p className="mb-4"><span>This Privacy Policy (Privacy Policy) describes how YAD-2-YOKRA, LLC (YAD-2-YOKRA,us or we) collects, uses and discloses information from its users, including with respect to the website located at https://www.YAD-2-YOKRA.com (the “Website”) and any related content, features, content, materials, applications, widgets and/or services (collectively, the “Services”).</span></p>
                <p className="mb-4"><span>BY USING THE SERVICES, YOU ACCEPT ALL OF THE PROVISIONS OF THE YAD-2-YOKRA TERMS OF USE AND THIS PRIVACY POLICY. IF YOU DO NOT ACCEPT THE YAD-2-YOKRA TERMS OF USE AND THIS PRIVACY POLICY, THEN YOU ARE NOT AUTHORIZED TO USE ANY OF YAD-2-YOKRA’S SERVICES.</span></p>
                <p className="mb-4"><span>For purposes of this Privacy Policy, “you” and “your” means you as the user of the Services. If you use the Services on behalf of a company, organization, or other entity, then “you” includes you and that entity.</span></p>
                <p className="mb-4"><span>We may collect the following categories of information about you that either directly or indirectly identifies you or could reasonably be used to identify you (collectively, “Personal Information”):</span></p>
                <p className="mb-4 font-bold"><span>Types of information We collect.</span></p>
                <p className="mb-4"><span>- Registration information you provide when you create an account, including your name, email address, telephone number, address, username, password, payment information, and other account information.</span></p>
                <p className="mb-4"><span>- Information you provide to us when you access or use the Services and each time you interact with the Services or YAD-2-YOKRA, for example, when you update information in your control panel, communicate with us by telephone or email, and order products or services. Such information includes your payment information. We also store information about the products you purchase or sell through the Services, such as the product information, date of purchase or sale, and information relating to any support issue.</span></p>
                <p className="mb-4"><span>- Usage, viewing, and technical data, including your IP address or device identifier when you use the Services. If you access your account from a mobile device, that mobile device may also provide us with details of your location. Most mobile devices allow you to disable this functionality.</span></p>
                <p className="mb-4"><span>- Information we receive from third parties, including analytics platforms, social media platforms, and advertising partners. For example, if you access the Services through a third-party platform or log-in, we may also collect your email address associated with that third party, (such as Facebook or Google Chrome) and any information you have made public in connection with that service or which the third party shares with partner services.</span></p>
                <p className="mb-4 font-bold"><span>How We collect Your information.</span></p>
                <p className="mb-4"><span>You may disable cookies by changing the settings on your browser. Check the help menu in your browser for further information. Remember that if you disable cookies it is likely to affect how the Services work and you may not be able to access or use certain areas of our Website or functionality. Unless you have adjusted your browser setting so that it will refuse cookies, our system will place cookies when you log on to the Services.</span></p>
                <p className="mb-4 font-bold"><span>Information You provide. </span></p>
                <p className="mb-4"><span>We collect the information you provide to us when you register with us, submit products to us, request products, services, or information from us, participate in activities through the Services, respond to customer surveys, or otherwise interact with us. Please keep in mind that when you post information on a third-party site or platform, the information you provide may be separately collected by the third-party site or platform. The information we collect is covered by this Privacy Policy and the information the third-party site or platform collects is subject to the third-party site or platform’s privacy practices. Privacy choices you make on the third-party site or platform will not apply to our use of the information we collect directly through our Services.</span></p>
                <p className="mb-4 font-bold"><span>Unique Identifiers.</span></p>
                <p className="mb-4"><span>We collect information through unique identifiers (such as IP address or your mobile device advertising identifier).</span></p>
                <p className="mb-4 font-bold"><span>Cookies.</span></p>
                <p className="mb-4"><span>We use “cookies” and other technologies to collect data that enable us to better understand and improve the usability, performance and effectiveness of our Website. Cookies are files sent to your browser and stored on your computer. We use cookies to gather general information about your visits to our Website, the files you have designated for backup, the configuration of your computer and your computer’s interaction with the Services, and store this information in log files. YAD-2-YOKRA uses this information to understand traffic and downloads on our Website, enabling us to improve the Website, provide the best online experience possible, and improve our customer service. We use the following types of cookies on our site:</span></p>
                <p className="mb-4"><span>- Strictly Necessary Cookies - These cookies are essential in order to enable you to move around our Website and use its features, such as accessing secure areas of the Website and remembering which files you have marked for backup. Without these cookies, services you have asked for, like security or e-billing, cannot be provided.</span></p>
                <p className="mb-4"><span>- Other Technologies - We may also use other Internet technologies, such as web beacons or pixel tags and other similar technologies, to deliver or communicate with cookies and analyze your use of the Services. We also may include web beacons in email messages so that we know when you have opened an email message received from YAD-2-YOKRA.</span></p>
                <p className="mb-4 font-bold"><span>Third-Party Analytics. </span></p>
                <p className="mb-4"><span>We use third parties’ analytic and tracking tools to better understand who is using the Services, how people are using the Services and how to improve the effectiveness of the Services and their content, and to help those parties serve more targeted advertising to you across the Internet or help us serve more targeted advertising to you. Those third-party companies may use cookies, pixel tags, or other technologies to collect and store certain information, such as time of visit, pages visited, time spent on each page of the Services, device identifiers, type of operating system used, and another website(s) you may have visited. They might combine information they collect from your interaction with our Services with Personal Information they collect from other sources. We do not have access to, nor control over, third parties’ use of cookies or other tracking technologies. We use Google Analytics, which is a web analytics tool that helps us understand how users engage with the Website. Like many services, Google Analytics uses first-party cookies to track user interactions, as in our case, where they are used to collect information about how users use our site. This information is used to compile reports and to help us improve our Website. The reports disclose website trends without identifying individual visitors. You can opt-out of Google Analytics without affecting how you visit our site – for more information on opting out of being tracked by Google Analytics across all websites you use, visit this Google page: <a className=" text-pink-400 underline" href="https://tools.google.com/dlpage/gaoptout">https://tools.google.com/dlpage/gaoptout.</a></span></p>
                <p className="mb-4"><span><strong>YouTube.</strong><br /><br /> By visiting and using the https://www.YAD-2-YOKRA.com website, the website user also agrees to be bound by the YouTube terms of service which can be found in the following link: <a className=" text-pink-400 underline" href="https://www.youtube.com/t/terms">https://www.youtube.com/t/terms</a></span></p>

            </div>
        </>
    )
}


export default Privacy
